#!/usr/bin/env bash
# Script to display information about subdomains

domain=$1
subdomain=$2

if [ -z "$domain" ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    subdomains=("$subdomain")
fi

for sub in "${subdomains[@]}"; do
    output=$(dig +short "$sub.$domain" | awk '{print $1}')
    record_type=$(dig "$sub.$domain" | awk '/ANSWER SECTION/{getline; print $4}')
    echo "The subdomain $sub is a $record_type record and points to $output"
done

